In [1]:
import pandas as pd
import numpy as np

In [107]:
# read excel file and specify the revenue (1) and cost (-1)
df = pd.read_excel('Topsis_Exercise.xlsx' , index_col='Mobile Phone')
impact= [1 , 1 , 1 , 1 , -1]
df

Ram  Memory  DisplaySize  Battery  Price
Mobile Phone                                          
A               4     128          6.5     3500  15000
B               6      64          6.4     3800  16000
C               6     128          6.8     4200  19000
D               8     256          7.0     5000  25000

In [56]:
# create matrix
data_mat = np.array(df)
data_mat

array([[4.00e+00, 1.28e+02, 6.50e+00, 3.50e+03, 1.50e+04],
       [6.00e+00, 6.40e+01, 6.40e+00, 3.80e+03, 1.60e+04],
       [6.00e+00, 1.28e+02, 6.80e+00, 4.20e+03, 1.90e+04],
       [8.00e+00, 2.56e+02, 7.00e+00, 5.00e+03, 2.50e+04]])

In [55]:
# normalizing the data
def vector_normalized():
    normalized_matrix = data_mat / np.sqrt(np.sum(data_mat ** 2 , axis = 0))
    return normalized_matrix
vector_normalized()

array([[0.32444284, 0.4       , 0.48658093, 0.42034651, 0.39163022],
       [0.48666426, 0.2       , 0.47909507, 0.45637621, 0.41773891],
       [0.48666426, 0.4       , 0.50903851, 0.50441581, 0.49606495],
       [0.64888568, 0.8       , 0.52401023, 0.60049501, 0.65271704]])

In [78]:
# specify the weighted matrix with entropy method
m = data_mat.shape[0]
def antropy_weighted(m):
    k = 1 / np.log(m)
    E = -k * np.sum(vector_normalized() * np.log(vector_normalized()) , axis=0)
    w = E / sum(E)
    return w
antropy_weighted(m)

array([0.20109574, 0.18416571, 0.2068576 , 0.20511708, 0.20276387])

In [96]:
data_wn = np.multiply(antropy_weighted(m) , vector_normalized())
data_wn

array([[0.06524407, 0.07366629, 0.10065296, 0.08622025, 0.07940846],
       [0.09786611, 0.03683314, 0.09910445, 0.09361056, 0.08470236],
       [0.09786611, 0.07366629, 0.10529848, 0.1034643 , 0.10058405],
       [0.13048815, 0.14733257, 0.1083955 , 0.12317178, 0.13234743]])

In [114]:
# specify the ideal matrix
data_wn = data_wn * impact
ideal_negative = np.max(data_wn , axis=0)
ideal = ideal_negative * impact
ideal

array([0.13048815, 0.14733257, 0.1083955 , 0.12317178, 0.07940846])

In [117]:
# specify the non-ideal matrix
nonideal_negative = np.min(data_wn , axis=0)
nonideal = nonideal_negative * impact
nonideal

array([0.06524407, 0.03683314, 0.09910445, 0.08622025, 0.13234743])

In [120]:
si_ideal = np.sqrt(np.sum(ideal - data_wn , axis=1) ** 2)
si_ideal

array([0.34242135, 0.34608455, 0.30908533, 0.21175589])

In [121]:
si_nonideal = np.sqrt(np.sum(nonideal - data_wn , axis=1) ** 2)
si_nonideal

array([0.17337424, 0.17703745, 0.14003822, 0.04270879])

In [148]:
cl = si_nonideal / (si_nonideal + si_ideal)
dictionary_cl ={'A': cl[0],
                'B': cl[1],
                'C': cl[2],
                'D': cl[3]}
dict(sorted(dictionary_cl.items() , key=lambda item: item[1] , reverse=True))

{'B': 0.3384247781801242,
 'A': 0.3361297491951908,
 'C': 0.31180334002888854,
 'D': 0.16783777948883427}

B is the best item